### ISSUE TITLE
Real estate data collection

### ISSUE THREAD

**Issue by TanPingZhi** [TanPingZhi/FTS-Macro-Forecasting#3]
convert to numpy
get monthly returns too

**Comment by TanPingZhi** [comment]
@Bawfen

**Comment by Bawfen** [comment]
@TanPingZhi Are we going to add a requirements.txt so we know what dependencies are needed?

**Comment by TanPingZhi** [comment]
Thats a good idea that would be helpful. Please do add if you have set the txt file up
